all: server stat joeServer
server: server.c
	gcc -o server server.c

stat: stat.cpp
	g++ -o stat stat.cpp

joeServer: joeServer.c
	gcc -o joeServer joeServer.c

sigint: sigint.cpp
	g++ -o sigint sigint.cpp

